name = "minor_apricot_marmot-c1ec"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "minor_apricot_marmot-c1ec_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "minor_apricot_marmot-c1ec.wasm"
command = "npm run build:release"
